# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: jeongmin
  #vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      {{ pool }}
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '{{ dockerfilePath }}'
        tags: |
          $(tag)

- stage : echo
  displayName: echo name
  jobs:
  - job: test
    displayName: test
    steps:
      - task: Gradle@3
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'build'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          sonarQubeRunAnalysis: false
          spotBugsAnalysis: false
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

- stage : script
  displayName: script name
  jobs:
  - job: test2
    displayName: test2
    steps:
      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'    
      - task: CmdLine@2
        inputs:
          script: |
            echo Write your commands here
            
            echo Hello world






